apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbs-enfinity-ui
  labels:
    name: cbs-enfinity-ui
spec:
  template:
    metadata:
      name: cbs-enfinity-ui-pd
      labels:
        type: cbs-enfinity-ui-lb
    spec:
      containers:
        - name: cbs-enfinity-ui-ct-v1
          image: actdocker123/cbs-micro-service:enfinity-cbs-ui-V1.0.20
          imagePullPolicy: IfNotPresent
          # Other configurations (resources, probes, etc.) are commented out for brevity
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TZ
              value: "Asia/Calcutta"
          envFrom:
            - configMapRef:
                name: cbsui-service-ip-config
          volumeMounts:
            - name: ssl-config
              mountPath: /opt/ssl
              readOnly: true
      volumes:
        - name: ssl-config
          hostPath:
            path: /opt/ssl
      imagePullSecrets:
        - name: cbs-enfinity
  replicas: 1
  selector:
    matchLabels:
      type: cbs-enfinity-ui-lb
---

apiVersion: v1
kind: Service
metadata:
  name: cbs-enfinity-ui-service
  labels:
    type: cbs-enfinity-ui-service-lb
spec:
  type: NodePort
  ports:
    - nodePort: 30009
      port: 3000
      targetPort: 3000
  selector:
    type: cbs-enfinity-ui-lb
