apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp  # Match the labels used in the selector
    spec:
      containers:
      - name: reactapp-container
        image: actdocker123/cicdpipeline:react-app-V1.056
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: sample-reactapp-service
spec:
  selector:
    app: reactapp
  ports:
    - nodePort: 30006 ###external access port
      port : 3000 ###cluster access port
      targetPort: 3000 ###pod/container access port

  type: NodePort
