apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  replicas: 1  # Number of pods to be created
  selector:
    matchLabels:
      app: reactapp-selector
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp-container
        image: actdocker123/cicdpipeline:react-app-V1.056
        ports:
        - containerPort: 3000

