apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1.0.1
spec:
  replicas: 1  # Number of pods to be created
  selector:
    matchLabels:
      app: 1.0.1
  template:
    metadata:
      labels:
        app: 1.0.1
    spec:
      containers:
      - name: 1.0.1
        image: actdocker123/cicdpipeline:1.0.1
        ports:
        - containerPort: 3000
