apiVersion: v1
kind: Service
metadata:
  name: sample-reactapp-service
spec:
  selector:
    app: sample-reactapp
  ports:
    - nodePort: 30006 ###external access port
      port : 3000 ###cluster access port
      targetPort: 3000 ###pod/container access port

  type: NortPort
