apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-reactapp-54
spec:
  replicas: 1  # Number of pods to be created
  selector:
    matchLabels:
      app: sample-reactapp-54
  template:
    metadata:
      labels:
        app: sample-reactapp-54
    spec:
      containers:
      - name: sample-reactapp-54
        image: actdocker123/cicdpipeline:sample-reactapp-54
        ports:
        - containerPort: 3000
