apiVersion: v1
kind: Service
metadata:
  name: sample-reactapp-service
spec:
  selector:
    app: sample-reactapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
