name: Update Image Tag

on:
  push:
    branches:
      - main

jobs:
  update_tag:
    runs-on: k8s-manifest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Image Tag
        id: extract_tag
        run: |
          TAG=$(grep 'image:' cbs-authentication-deploy-service.yaml | awk -F '[:]' '{print $3}')
          echo "::set-output name=tag::$TAG"

      - name: Increment Tag
        id: increment_tag
        run: |
          TAG="enfinity-authenticationservice-V1.0.11"

          # Extracting components from TAG
          IFS='-' read -r FIRST_PARA SECOND_PARA VERSION <<< "$TAG"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          # Incrementing PATCH
          NEW_PATCH=$((PATCH + 1))

          # Constructing NEW_TAG
          NEW_TAG="$FIRST_PARA-$SECOND_PARA-$MAJOR.$MINOR.$NEW_PATCH"

          echo "$NEW_TAG"

          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Store New Tag
        id: store_tag
        run: echo "NEW_TAG=${{ steps.increment_tag.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Use New Tag
        run: |
          echo "New tag is ${{ steps.increment_tag.outputs.new_tag }}"
